export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpg",
    username: "Michael Scoffield",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpg",
    username: "Johnson Clart",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpg",
    username: "Magret Jack",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpg",
    username: "Ambrose Bukki",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpg",
    username: "Johnson Jay",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Tosin Abba",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpg",
    username: "Martins Jones",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpg",
    username: "Shade Blade",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Lynda Clara",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Amaka Ukah",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "If only I could become a superman.",
    photo: "assets/post/1.jpg",
    date: "9 mins ago",
    userId: 1,
    like: 7,
    comment: 6,
  },
  {
    id: 2,
    photo: "assets/post/2.jpg",
    date: "20 mins ago",
    userId: 2,
    like: 2,
    comment: 109,
  },
  {
    id: 3,
    desc: "It's never too late to start until it is off.",
    photo: "assets/post/3.jpg",
    date: "3 hour ago",
    userId: 3,
    like: 20,
    comment: 0,
  },
  {
    id: 4,
    photo: "assets/post/4.jpg",
    date: "5 hours ago",
    userId: 4,
    like: 0,
    comment: 0,
  },
  {
    id: 5,
    photo: "assets/post/5.jpg",
    date: "6 hours ago",
    userId: 5,
    like: 120,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "2 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "life is never a bed of roses. Get that!",
    photo: "assets/post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Be the change you clamour.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 1,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
